# input data
base_dir: /home/hbr/code/3DV-2022
data_dir: ${base_dir}/data/chair
dtype: "voxel" # "point" "voxel"
n_points: 2048
# n_points: 1024

# vision model
arch: resnet18

# training
lr: 0.0004
max_iter: 10000

# dataloader
batch_size: 10
num_workers: 0

# logger
log_freq: 1000

# checkpoint
save_freq: 100
load_checkpoint: False

# eval
vis_freq: 10
load_eval_checkpoint: True

