# input data
base_dir: /home/hbr/code/3DV-2022
data_dir: ${base_dir}/data/chair
dtype: "point" # "point" "voxel"
n_points: 4096

# vision model
arch: resnet18

# training
# lr: 0.0001
lr: 1e-5
max_iter: 1000

# dataloader
batch_size: 10
num_workers: 2

# logger
log_freq: 1000

# checkpoint
save_freq: 200
load_checkpoint: False

# eval
vis_freq: 10
load_eval_checkpoint: True

